using System.Collections;
using System.Collections.Generic;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

public class MenueScript : MonoBehaviour
{
    //TO DO:    Add Canvas for About

    //Beim Start neue Szene laden oder lieber bei geladener Szene als Canvas nutzen?

    AudioManager audioManager;

    public void Credits()
    {
        SceneManager.LoadSceneAsync(2);
    }

    //Nutzen wenn Menü eigene Szene hat

    public void StartGame()
    {
        SceneManager.LoadSceneAsync(1);
    }

    //Bleibt immer gleich :D

        public void Quit()
        {
            Application.Quit();
        }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            Quit();
        }
    }
}
