using UnityEngine;

public class AudioManager : MonoBehaviour

    //wird noch barbeitet, ist gerade nur ein Copy Past aus Seascape
{
    [Header("Audio Source")]
    [SerializeField] AudioSource m_Source;
    [SerializeField] AudioSource SFXSource;


    [Header("Audio Clip")]
    public AudioClip activeBackground;
    public AudioClip buttonSelect;
    public AudioClip success;
    public AudioClip filter;
    public AudioClip interactBottle;

    public void Start()
    {
        m_Source.clip = activeBackground;
        m_Source.Play();
    }

    public void PlaySFX(AudioClip clip)
    {
        SFXSource.PlayOneShot(clip);
    }
}
